
- name: Gather EC2 Metadata Information
  action: ec2_facts

- name: Install packages needed for analyzing network traffic
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
     - tcpdump.x86_64
     - tcpick.x86_64
  when: ansible_os_family == 'RedHat'

- name: Start tcpdump job to track connections based on network filter
  become: yes
  become_method: sudo
  shell: >
     nohup tcpdump -i any -w ssh-triage-{{ ansible_ec2_instance_id }}.pcap -Als0 {{ tcpdump_filter }} 2>/dev/null &
  when: ansible_os_family == 'RedHat'
